//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeGestionDeHorariosDeTutoriasAcademicas_Cliente.ServicioSesionTutoria {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SesionDeTutoriaDTO", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
    [System.SerializableAttribute()]
    public partial class SesionDeTutoriaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaDeSesionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPeriodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSesionDeTutoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroDeSesionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDeSesion {
            get {
                return this.FechaDeSesionField;
            }
            set {
                if ((this.FechaDeSesionField.Equals(value) != true)) {
                    this.FechaDeSesionField = value;
                    this.RaisePropertyChanged("FechaDeSesion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPeriodo {
            get {
                return this.IdPeriodoField;
            }
            set {
                if ((this.IdPeriodoField.Equals(value) != true)) {
                    this.IdPeriodoField = value;
                    this.RaisePropertyChanged("IdPeriodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSesionDeTutoria {
            get {
                return this.IdSesionDeTutoriaField;
            }
            set {
                if ((this.IdSesionDeTutoriaField.Equals(value) != true)) {
                    this.IdSesionDeTutoriaField = value;
                    this.RaisePropertyChanged("IdSesionDeTutoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroDeSesion {
            get {
                return this.NumeroDeSesionField;
            }
            set {
                if ((this.NumeroDeSesionField.Equals(value) != true)) {
                    this.NumeroDeSesionField = value;
                    this.RaisePropertyChanged("NumeroDeSesion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioSesionTutoria.ISesionTutoriaServicio", CallbackContract=typeof(SistemaDeGestionDeHorariosDeTutoriasAcademicas_Cliente.ServicioSesionTutoria.ISesionTutoriaServicioCallback))]
    public interface ISesionTutoriaServicio {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISesionTutoriaServicio/RegistrarSesionDeTutoria")]
        void RegistrarSesionDeTutoria(SistemaDeGestionDeHorariosDeTutoriasAcademicas_Cliente.ServicioSesionTutoria.SesionDeTutoriaDTO sesion);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISesionTutoriaServicio/RegistrarSesionDeTutoria")]
        System.Threading.Tasks.Task RegistrarSesionDeTutoriaAsync(SistemaDeGestionDeHorariosDeTutoriasAcademicas_Cliente.ServicioSesionTutoria.SesionDeTutoriaDTO sesion);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISesionTutoriaServicio/ObtenerSesionesPorPeriodo")]
        void ObtenerSesionesPorPeriodo(int idPeriodo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISesionTutoriaServicio/ObtenerSesionesPorPeriodo")]
        System.Threading.Tasks.Task ObtenerSesionesPorPeriodoAsync(int idPeriodo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISesionTutoriaServicioCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISesionTutoriaServicio/NotificarSesionRegistrada", ReplyAction="http://tempuri.org/ISesionTutoriaServicio/NotificarSesionRegistradaResponse")]
        void NotificarSesionRegistrada(SistemaDeGestionDeHorariosDeTutoriasAcademicas_Cliente.ServicioSesionTutoria.SesionDeTutoriaDTO sesion);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISesionTutoriaServicio/NotificarError")]
        void NotificarError(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISesionTutoriaServicio/NotificarSesionesPorPeriodo", ReplyAction="http://tempuri.org/ISesionTutoriaServicio/NotificarSesionesPorPeriodoResponse")]
        void NotificarSesionesPorPeriodo(SistemaDeGestionDeHorariosDeTutoriasAcademicas_Cliente.ServicioSesionTutoria.SesionDeTutoriaDTO[] sesiones);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISesionTutoriaServicioChannel : SistemaDeGestionDeHorariosDeTutoriasAcademicas_Cliente.ServicioSesionTutoria.ISesionTutoriaServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SesionTutoriaServicioClient : System.ServiceModel.DuplexClientBase<SistemaDeGestionDeHorariosDeTutoriasAcademicas_Cliente.ServicioSesionTutoria.ISesionTutoriaServicio>, SistemaDeGestionDeHorariosDeTutoriasAcademicas_Cliente.ServicioSesionTutoria.ISesionTutoriaServicio {
        
        public SesionTutoriaServicioClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public SesionTutoriaServicioClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public SesionTutoriaServicioClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SesionTutoriaServicioClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SesionTutoriaServicioClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void RegistrarSesionDeTutoria(SistemaDeGestionDeHorariosDeTutoriasAcademicas_Cliente.ServicioSesionTutoria.SesionDeTutoriaDTO sesion) {
            base.Channel.RegistrarSesionDeTutoria(sesion);
        }
        
        public System.Threading.Tasks.Task RegistrarSesionDeTutoriaAsync(SistemaDeGestionDeHorariosDeTutoriasAcademicas_Cliente.ServicioSesionTutoria.SesionDeTutoriaDTO sesion) {
            return base.Channel.RegistrarSesionDeTutoriaAsync(sesion);
        }
        
        public void ObtenerSesionesPorPeriodo(int idPeriodo) {
            base.Channel.ObtenerSesionesPorPeriodo(idPeriodo);
        }
        
        public System.Threading.Tasks.Task ObtenerSesionesPorPeriodoAsync(int idPeriodo) {
            return base.Channel.ObtenerSesionesPorPeriodoAsync(idPeriodo);
        }
    }
}
