//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeGestionDeHorariosDeTutoriasAcademicas_Cliente.ServicioReporte {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReporteTutoriaDTO", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
    [System.SerializableAttribute()]
    public partial class ReporteTutoriaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] AsuntosTratadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaTutoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSesionDeTutoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroAsuntosNoAtendidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroTutoradosAtendidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TiempoPromedioTutoriasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] AsuntosTratados {
            get {
                return this.AsuntosTratadosField;
            }
            set {
                if ((object.ReferenceEquals(this.AsuntosTratadosField, value) != true)) {
                    this.AsuntosTratadosField = value;
                    this.RaisePropertyChanged("AsuntosTratados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaTutoria {
            get {
                return this.FechaTutoriaField;
            }
            set {
                if ((this.FechaTutoriaField.Equals(value) != true)) {
                    this.FechaTutoriaField = value;
                    this.RaisePropertyChanged("FechaTutoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSesionDeTutoria {
            get {
                return this.IdSesionDeTutoriaField;
            }
            set {
                if ((this.IdSesionDeTutoriaField.Equals(value) != true)) {
                    this.IdSesionDeTutoriaField = value;
                    this.RaisePropertyChanged("IdSesionDeTutoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroAsuntosNoAtendidos {
            get {
                return this.NumeroAsuntosNoAtendidosField;
            }
            set {
                if ((this.NumeroAsuntosNoAtendidosField.Equals(value) != true)) {
                    this.NumeroAsuntosNoAtendidosField = value;
                    this.RaisePropertyChanged("NumeroAsuntosNoAtendidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroTutoradosAtendidos {
            get {
                return this.NumeroTutoradosAtendidosField;
            }
            set {
                if ((this.NumeroTutoradosAtendidosField.Equals(value) != true)) {
                    this.NumeroTutoradosAtendidosField = value;
                    this.RaisePropertyChanged("NumeroTutoradosAtendidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TiempoPromedioTutorias {
            get {
                return this.TiempoPromedioTutoriasField;
            }
            set {
                if ((this.TiempoPromedioTutoriasField.Equals(value) != true)) {
                    this.TiempoPromedioTutoriasField = value;
                    this.RaisePropertyChanged("TiempoPromedioTutorias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioReporte.IReporteServicio", CallbackContract=typeof(SistemaDeGestionDeHorariosDeTutoriasAcademicas_Cliente.ServicioReporte.IReporteServicioCallback))]
    public interface IReporteServicio {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IReporteServicio/ObtenerReportesDeTutorias")]
        void ObtenerReportesDeTutorias();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IReporteServicio/ObtenerReportesDeTutorias")]
        System.Threading.Tasks.Task ObtenerReportesDeTutoriasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReporteServicioCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IReporteServicio/RecibirReportesDeTutorias")]
        void RecibirReportesDeTutorias(SistemaDeGestionDeHorariosDeTutoriasAcademicas_Cliente.ServicioReporte.ReporteTutoriaDTO[] reportes);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IReporteServicio/NotificarError")]
        void NotificarError(string mensaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReporteServicioChannel : SistemaDeGestionDeHorariosDeTutoriasAcademicas_Cliente.ServicioReporte.IReporteServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReporteServicioClient : System.ServiceModel.DuplexClientBase<SistemaDeGestionDeHorariosDeTutoriasAcademicas_Cliente.ServicioReporte.IReporteServicio>, SistemaDeGestionDeHorariosDeTutoriasAcademicas_Cliente.ServicioReporte.IReporteServicio {
        
        public ReporteServicioClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ReporteServicioClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ReporteServicioClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteServicioClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteServicioClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ObtenerReportesDeTutorias() {
            base.Channel.ObtenerReportesDeTutorias();
        }
        
        public System.Threading.Tasks.Task ObtenerReportesDeTutoriasAsync() {
            return base.Channel.ObtenerReportesDeTutoriasAsync();
        }
    }
}
